---
server:
    install: '1'
    packages: [vim, git]
    timezone: America/Sao_Paulo
    locale: pt_BR.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: api, ip: 192.168.33.02, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: api.vb
mysql:
    install: '1'
    root_password: senha
    database: api
    user: usuario
    password: senha
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-common, php5-mysql]

